.Dd December 25, 2019
.Dt ZOKETED 8
.Os
.Sh NAME            \" Section Header - required - don't modify
.Nm zoketed
.Nd Zokete SOCKS5 server
https://github.com/matricali/zokete
.Sh SYNOPSIS                \" Section Header - required - don't modify
.Nm
.Op Fl hv                   \" [-hv]
.Op Fl -help              \" [--help]
.Op Fl -version           \" [--version]
.Op Fl p Ar port            \" [-p port]
.Op Fl -port Ar port      \" [-p port]
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Nm
is a simple SOCKS5 server.
.Sh OPTIONS
The following options are available:
.Bl -tag -width XXrXXXrecursiveX
.It Fl h , -help
Shows help screen
.It Fl v, Fl Fl version
Version
.It Fl p, Fl Fl port
Listening port
.El                      \" Ends the list
.\" .Sh BUGS              \" Document known, unremedied bugs
.\" .Sh HISTORY           \" Document history if command behaves in a unique manner
.Sh AUTHOR
.Nm
was written by
.An Jorge Matricali Aq Mt jorgematricali@gmail.com
.Pp
Permission is granted to copy, distribute and/or modify this
document under the terms of the GNU Free
Documentation License, Version 1.1 or any later version
published by the Free Software Foundation; with no Invariant
Sections, no Front-Cover Texts and no Back-Cover Texts.
